name: frp
description: Expose a local server behind a NAT or firewall to the internet.
version: 1.0.4
url: https://github.com/hannpet/addon-frpc
startup: application
boot: auto
host_network: true
slug: frp
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
map:
  - config:rw
  - ssl:rw
  - backup:rw

options:
  proto: tcp
  server_addr: null
  server_port: 7000
  token_key: null
  local_port: 80
  subdomain: hassio

schema:
  proto: list(tcp|kcp|websocket)
  server_addr: str
  server_port: port
  token_key: str
  local_port: port
  subdomain: str